import Head from 'next/head'
import Script from 'next/script'

// components 
import Header from '@/components/header'
import Promos from '@/components/promos'
import MisionVision from '@/components/misionVision'
import Productos from '@/components/productos'
import Sucursales from '@/components/sucursales'
import Contact from '@/components/contact'
import Footer from '@/components/footer'

export default function Home() {
    return (
        <>
            <Head>
                <title>Panaderia Dulce Catalina</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mt-4">
                <div className="section container">

                    <Header></Header>

                    <Promos></Promos>

                    <MisionVision></MisionVision>

                    <Productos></Productos>

                    <Sucursales></Sucursales>

                    <Contact></Contact>

                </div>


            </main>

            <Footer></Footer>

  
        </>
    )
}
