import Head from 'next/head'
import Script from 'next/script'

// components 
import Header from '@/components/header'
import Promos from '@/components/promos'
import MisionVision from '@/components/misionVision'
import Productos from '@/components/productos'
import Sucursales from '@/components/sucursales'
import Contact from '@/components/contact'
import Footer from '@/components/footer'

export default function Home() {
    return (
        <>
            <Head>
                <title>Panaderia Dulce Catalina</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
        //icons
                <Script src="https://kit.fontawesome.com/d53a7fc004.js" crossorigin="anonymous" />
                {/* //bootstrap
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" /> */}
        //scroll Reveal
                <Script src="https://unpkg.com/scrollreveal" />
        // js propio
                <Script src="app.js" />
            </Head>
            <main className="container mt-4">
                <div className="section container">

                    <Header></Header>

                    <Promos></Promos>

                    <MisionVision></MisionVision>

                    <Productos></Productos>

                    <Sucursales></Sucursales>

                    <Contact></Contact>

                </div>


            </main>

            <Footer></Footer>
            
            {/* //JavaScript Bundle with Popper */}
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous" />
        </>
    )
}
